added step to commit latest abi json file

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -73,7 +73,13 @@ jobs:
 
       - name: Generate ABI for frontend
         #working-directory: ./contracts
-        run: jq '.abi' out/ParametricCropInsurance.sol/ParametricCropInsurance.json
+        run: |
+          jq '.abi' out/ParametricCropInsurance.sol/ParametricCropInsurance.json > ../../abi_latest.json
+          git config user.name "GitHub Actions"
+          git add .
+          git commit -m "CI:  commit latest abi [skip ci]" || echo "Nothing to commit"
+          git push || echo "Push failed"
+
 
 
       - name: Deploy 
